# Generated by Django 5.2.3 on 2025-06-23 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_receiptupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptupload',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
