# Generated by Django 5.2.3 on 2025-06-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_categorybudget_savinggoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking')], default='cash', max_length=50),
        ),
    ]
