# Generated by Django 5.2.3 on 2025-06-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_budget_alter_expense_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='budget',
        ),
        migrations.AlterField(
            model_name='categorybudget',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('bills', 'Bills'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='categorybudget',
            name='month',
            field=models.DateField(help_text='Use the 1st of the month to represent that month'),
        ),
    ]
